### PR TITLE
fix(blocks): preserve block ids when pasting

### LINKED ISSUE #6366: Block id mutates when pasting text
Every time text is pasted, a new block instance is created. This issue can result in a poor collaboration experience.

https://github.com/toeverything/blocksuite/assets/18554747/75973f42-f7d5-4e4a-8a32-1e5bad92140a

### PR DESCRIPTION
**Pull request by fourdim**
This closes #6366, closes BS-139.

This PR merges part of snapshot to the `fromPointState.model`. The first snapshot is deleted after being merged to the `fromPointState.model`, so the snapshot could probably be an empty array.
We delete snapshot from snapshots instead of block from blocks mainly because that if blocks are deleted immediately after they are created will cause errors as operations in `connectcallback` does not have any corresponding blocks attached.

### CODE REVIEW

**Comment by fourdim** [comment]
* **#7386** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7386?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fourdim and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Saul-Mirone** [comment]
Can you please also re-check the `clipboard.spec.ts`? we have several `test.skip` now and I think it's time to decide if we should fix or remove them.

File: packages/blocks/src/root-block/clipboard/middlewares/paste.ts [hunk 1]
```diff
@@ -127,14 +151,16 @@ class PasteTr {
...
-    if (toLanguage !== 'Plain Text') {
-      this.firstSnapshot.props.language = toLanguage;
-    }
-    const deltas: DeltaOperation[] = [...fromDelta];
+    const { toDelta } = this._getDeltas();
+    const deltas: DeltaOperation[] = [
+      { retain: this.fromPointState.point.index },
+      this.fromPointState.text.length - this.fromPointState.point.index
+        ? {
+            delete:
```
Comment (Saul-Mirone) [inline packages/blocks/src/root-block/clipboard/middlewares/paste.ts:159]: :+1:

File: packages/blocks/src/root-block/clipboard/middlewares/paste.ts [hunk 2]
```diff
@@ -148,62 +174,139 @@ class PasteTr {
...
+    );
+  };
+
+  private async _transformLinkDelta(
+    delta: DeltaOperation[],
+    linkToDocId: Map<string, string | null>,
+    quickSearchService: QuickSearchService
+  ) {
+    const needToConvert = new Map<DeltaOperation, string>();
+    for (const op of delta) {
```
Comment (Saul-Mirone) [inline packages/blocks/src/root-block/clipboard/middlewares/paste.ts:254]: Let's use `forEach` here.

File: packages/blocks/src/root-block/clipboard/middlewares/paste.ts [hunk 3]
```diff
@@ -219,50 +322,73 @@ class PasteTr {
...
 
-    const lastModel = this.std.doc.getBlockById(this.lastSnapshot.id);
-    assertExists(lastModel);
-
-    if (!this.to) {
-      this.std.doc.deleteBlock(this.fromPointState.model, {
-        bringChildrenTo: lastModel,
-      });
+    if (this.to) {
+      const [_, context] = this.std.command
```
Comment (Saul-Mirone) [inline packages/blocks/src/root-block/clipboard/middlewares/paste.ts:326]: Can be shorten with:

```ts
this.std.command.exec('getSelectedModels', { types: ['text'] })
```

File: packages/blocks/src/root-block/clipboard/middlewares/paste.ts [hunk 4]
```diff
@@ -407,10 +499,21 @@ export const pasteMiddleware = (std: EditorHost['std']): JobMiddleware => {
       }
     });
     slots.afterImport.on(payload => {
+      if (payload.type === 'slice') {
+        const [_, context] = std.command
```
Comment (Saul-Mirone) [inline packages/blocks/src/root-block/clipboard/middlewares/paste.ts:503]: Same here

File: tests/clipboard.spec.ts [hunk 5]
```diff
@@ -1373,7 +1373,9 @@ test(scoped`clipboard copy multi selection`, async ({ page }) => {
   await focusRichText(page, 1);
   await pasteByKeyboard(page);
   await waitNextFrame(page);
-  await assertRichTexts(page, ['abc', 'defbc', 'd']);
+  await type(page, 'cursor');
+  await waitNextFrame(page);
+  await assertRichTexts(page, ['abc', 'defbc', 'dcursor']);
 });
```
Comment (Saul-Mirone) [inline tests/clipboard.spec.ts:1380]: I think we need to add more test cases to prevent furthur changes break the current behavior.

File: tests/clipboard.spec.ts [hunk 6]
```diff
@@ -1373,7 +1373,9 @@ test(scoped`clipboard copy multi selection`, async ({ page }) => {
...
 
 test.skip(scoped`clipboard copy nested items`, async ({ page }) => {
```
Comment (Saul-Mirone) [inline tests/clipboard.spec.ts:1381]: Can we recheck the skipped cases? Either re-enable them, remove them or fix them.

**Review by Saul-Mirone — APPROVED** [review]

File: packages/blocks/src/root-block/clipboard/middlewares/paste.ts (hunk 2 above)
Comment (fourdim) [reply packages/blocks/src/root-block/clipboard/middlewares/paste.ts:254]: According to [`no-misused-promises`](https://typescript-eslint.io/rules/no-misused-promises/):
```ts
// incorrect
[1, 2, 3].forEach(async value => {
  await fetch(`/${value}`);
});

// correct
for (const value of [1, 2, 3]) {
  await doSomething(value);
}
```

Comment (Saul-Mirone) [reply packages/blocks/src/root-block/clipboard/middlewares/paste.ts:254]: Didn't notice the await here, sorry

**Comment by fourdim** [comment]
More test cases will be added in a separate PR.
