### PR TITLE
fix: render `selectedRects` based on viewport scroll

### LINKED ISSUE #330: recalulate selected rect when resize/scroll the page

### LINKED ISSUE #989: Block selection disappear after scrolling
Block selection disappear after scrolling, and it is a temp fix in https://github.com/toeverything/blocksuite/blob/3e6dd8281b9c706448c57ec5e21cfca4f24daadd/packages/blocks/src/page-block/default/default-page-block.ts#L438-L439 to prevent it become misplaced.

The root issue is that block selections are `position:fixed` and will misplace if default viewport width changes or scrolling

https://user-images.githubusercontent.com/5123601/216752351-8c398ab5-0ca0-4094-92aa-c63f14be4cad.mp4

### PR DESCRIPTION
**Pull request by pingren**
Will close https://github.com/toeverything/blocksuite/issues/330

FYI: `selectedEmbedContainer` and `embedEditingContainer` have a similar issue, but not addressed in this PR. If this PR merged, then we could implement the fix later.

### CODE REVIEW

File: packages/blocks/src/page-block/default/default-page-block.ts [hunk 1]
```diff
@@ -387,6 +396,14 @@ export class DefaultPageBlockComponent
     );
   };
 
+  private _getViewportScrollOffset() {
+    const container = this.children[0];
```
Comment (pingren) [inline packages/blocks/src/page-block/default/default-page-block.ts:400]: Actually, I don't like getting child node by arbitrary index, suggestions welcome.

File: packages/blocks/src/page-block/default/components.ts [hunk 2]
```diff
@@ -95,9 +100,10 @@ export function SelectedRectsContainer(rects: DOMRect[]) {
     <div class="affine-page-selected-rects-container">
       ${rects.map(rect => {
         const style = {
+          position: 'absolute',
           display: 'block',
-          left: rect.left + 'px',
-          top: rect.top + 'px',
+          left: BLOCK_CHILDREN_CONTAINER_PADDING_LEFT + 'px',
```
Comment (himself65) [inline packages/blocks/src/page-block/default/components.ts]: incorrect padding in nested list

image

**Review by himself65 — CHANGES_REQUESTED** [review]

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
LGTM, the test cases could be added later
