### PR TITLE
fix(edgeless): show curve icon on resize handle hover before scaling starts

### LINKED ISSUE #6034: improvement the scale detail
when hover, should show the curve icon, and dragging, show the percentage: 

shot-2024-01-19-16 04 49

hover: 
shot-2024-01-19-16 34 38@2x

active:

shot-2024-01-19-16 34 54@2x

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #6034 

Changes:
- For Note - will show curve icon on hover if shift is pressed
- For Image / Attachment / Bookmark / Embed-* - show curve icon on hover

Curve icon and scale percent will always show while scaling.

### CODE REVIEW

File: packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts [hunk 1]
```diff
@@ -397,10 +417,13 @@ export class EdgelessSelectedRect extends WithDisposable(LitElement) {
   private _isResizing = false;
 
   @state()
-  private _dragDirection: HandleDirection | null = null;
+  private _mode: 'resize' | 'scale' | 'rotate' = 'resize';
 
   @state()
-  private _scalePercent: string | null = null;
+  private _scalePercent: string | undefined = undefined;
```
Comment (doodlewind) [inline packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts:423]: Guess using `private _scalePercent?: string;` could be semantically cleaner.

Comment (AyushAgrawal-A2) [reply packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts]: @doodlewind 
Done

**Review by doodlewind — APPROVED** [review]
