### PR TITLE
fix(page): `getPreviousBlock` not works as expected when there are several notes

### LINKED ISSUE #5100: Delete at the start of second note will jump to title
https://github.com/toeverything/blocksuite/assets/50035259/e0674a6d-dcd3-43e2-938c-ed12190413dc

### PR DESCRIPTION
**Pull request by Flrande**
Close #5100

### CODE REVIEW

File: packages/blocks/src/_common/utils/query.ts [hunk 1]
```diff
@@ -90,46 +90,48 @@ export function getNextBlock(
...
-  model: BaseBlockModel,
-  map: Record<string, true> = {}
-): BaseBlockModel | null {
-  if (model.id in map) {
-    throw new Error(
-      "Can't get previous block! There's a loop in the block tree!"
-    );
-  }
-  map[model.id] = true;
+export function getPreviousBlock(model: BaseBlockModel): BaseBlockModel | null {
```
Comment (Saul-Mirone) [inline packages/blocks/src/_common/utils/query.ts:95]: I think we should use the `getNextBlockCommand` instead of this one.

Comment (Flrande) [reply packages/blocks/src/_common/utils/query.ts:95]: This relates to the refactoring of `rich-text-operations.ts`.

**Review by doodlewind — APPROVED** [review]
