### PR TITLE
fix(edgeless): frame container zindex

### LINKED ISSUE #5086: Frame layers are messed up
https://github.com/toeverything/blocksuite/assets/144991896/d29d43c7-694e-46f8-975f-fb45b84bc653

Image

### PR DESCRIPTION
**Pull request by regischen**
close #5086

### CODE REVIEW

File: packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts [hunk 1]
```diff
@@ -54,6 +54,12 @@ export class EdgelessFramesContainer extends WithDisposable(LitElement) {
   @property({ attribute: false })
   surface!: SurfaceBlockComponent;
 
+  override connectedCallback(): void {
+    super.connectedCallback();
+    this.style.position = 'absolute';
```
Comment (doodlewind) [inline packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts:59]: Can this be declared as static CSS?

Comment (regischen) [reply packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts:59]: okay, let me try whether removing `createRenderRoot` will bring impact.
https://github.com/toeverything/blocksuite/blob/6ba0419a97e5977093cf22e985aa47a332de6047/packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts#L72C1-L74C4

Comment (regischen) [reply packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts:62]: because this
https://github.com/toeverything/blocksuite/blob/6ba0419a97e5977093cf22e985aa47a332de6047/packages/blocks/src/frame-block/frame-block.ts#L39-L41
in order to access parentBlockElement, we can't put blockelement in shadow-root. so static styles will not work.

Comment (doodlewind) [reply packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts:62]: In this case, why not use `ShadowlessElement`?

**Review by doodlewind — APPROVED** [review]
