### PR TITLE
fix(edgeless): fix incorrect connector handle position on zooming

### LINKED ISSUE #3395: Incorrect connector handle position when zoom
https://github.com/toeverything/blocksuite/assets/58546692/71e0e979-7fd8-42ab-a1c7-6bff2705d94a

### PR DESCRIPTION
**Pull request by regischen**
close #3395 
also refactor original component, using _disposables

### CODE REVIEW

File: packages/blocks/src/page-block/edgeless/components/connector/connector-handler.ts [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+import type { ConnectorElement } from '@blocksuite/phasor';
+import { DisposableGroup } from '@blocksuite/store';
+import { css, html, LitElement } from 'lit';
+import { customElement, property, query } from 'lit/decorators.js';
+import { styleMap } from 'lit/directives/style-map.js';
+
+import type { EdgelessPageBlockComponent } from '../../edgeless-page-block.js';
+
+@customElement('edgeless-connector-handler')
+export class EdgelessConnectorHandler extends WithDisposable(LitElement) {
```
Comment (doodlewind) [inline packages/blocks/src/page-block/edgeless/components/connector/connector-handler.ts:11]: Should be *handle* (as noun) rather than *handler*.

Comment (regischen) [reply packages/blocks/src/page-block/edgeless/components/connector/connector-handler.ts:11]: ok, I thought handler was noun :)

**Review by doodlewind — APPROVED** [review]
