### PR TITLE
fix(blocks): fix link mock selection offset

### LINKED ISSUE #1570: Mock selection range created by link popup has wrong offset in AFFiNE
https://user-images.githubusercontent.com/18554747/223690925-cc418d9f-86f9-4ff7-a67a-35be3084d3d2.mov

### PR DESCRIPTION
**Pull request by Flrande**
Close #1570

### CODE REVIEW

File: packages/blocks/src/__internal__/rich-text/link-node/create-link.ts [hunk 1]
```diff
@@ -45,7 +45,22 @@ export function createLink(page: Page) {
   // mock a selection style
   const range = getCurrentNativeRange();
   const rects = Array.from(range.getClientRects());
-  const mockSelection = new LinkMockSelection(rects);
+
+  const container = document.querySelector('.affine-editor-container');
```
Comment (lawvs) [inline packages/blocks/src/__internal__/rich-text/link-node/create-link.ts:49]: To prepare for the possibility of multiple editors in the future, you should use the method from 'query.ts'.

Comment (Flrande) [reply packages/blocks/src/__internal__/rich-text/link-node/create-link.ts:49]: I will update #1572 and #1561 later.
