### PR TITLE
fix: dispose quill keyboard handler before block selection

### LINKED ISSUE #633: Unable to delete in block-level selection after selecting code block
The code block can't be deleted by backspace if it's under block-level selection:

image

### PR DESCRIPTION
**Pull request by thorseraq**
Fixes #633

### CODE REVIEW

File: packages/blocks/src/page-block/default/selection-manager.ts [hunk 1]
```diff
@@ -256,6 +256,8 @@ export class DefaultSelectionManager {
     this.state.resetStartRange(e);
     this.state.refreshRichTextBoundsCache(this._mouseRoot);
     resetNativeSelection(null);
+    // deactivate quill keyboard event handler
+    (document.activeElement as HTMLTextAreaElement).blur();
```
Comment (doodlewind) [inline packages/blocks/src/page-block/default/selection-manager.ts:260]: I think the Quill instance is an `HTMLDivElement`.

Comment (thorseraq) [reply packages/blocks/src/page-block/default/selection-manager.ts:260]: How about this

```typescript
if (activeElement && 'blur' in activeElement && typeof activeElement['blur'] === 'function') {
  // deactivate quill keyboard event handler
    activeElement.blur();
  }
```

Comment (doodlewind) [reply packages/blocks/src/page-block/default/selection-manager.ts:260]: This looks too verbose. `as HTMLDivElement` may be semantically better, otherwise, it may indicate that the instance here is the page title.

Comment (thorseraq) [reply packages/blocks/src/page-block/default/selection-manager.ts:260]: OK, Get that!
