### PR TITLE
fix(edgeless): auto add frame on click when no frame exists

### LINKED ISSUE #2846: Deleting the last/only object (in Edgeless) breaks page mode
After deleting the last object/frame in Edgeless mode, the Page mode breaks: it's empty and you cannot type or insert from Block Hub anything to it. You can only turn to Edgeless mode again to add something to recover the Page mode.

feedback (1)

### PR DESCRIPTION
**Pull request by regischen**
Closes #2846

### CODE REVIEW

File: packages/blocks/src/page-block/default/selection-manager/selection-manager.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ import {
   isEmbed,
   isImage,
   isInsidePageTitle,
+  isInTitleBlock,
```
Comment (doodlewind) [inline packages/blocks/src/page-block/default/selection-manager/selection-manager.ts:39]: Actually we don't have a title block, it's just the title field in the page block. And can we reuse the `isInsidePageTitle` method instead of adding a new one?

File: packages/blocks/src/page-block/default/selection-manager/selection-manager.ts [hunk 2]
```diff
@@ -194,6 +197,15 @@ export class DefaultSelectionManager extends AbstractSelectionManager<DefaultPag
     );
   }
 
+  private _checkHasAnyFrameBlock() {
```
Comment (doodlewind) [inline packages/blocks/src/page-block/default/selection-manager/selection-manager.ts:200]: Semantically, a `checkSomething` method should not perform mutaions.

File: packages/store/src/workspace/page.ts [hunk 3]
```diff
@@ -203,6 +203,10 @@ export class Page extends Space<FlatBlockMap> {
     );
   }
 
+  hasFrameBlock() {
```
Comment (doodlewind) [inline packages/store/src/workspace/page.ts:206]: We should avoid adding page level API that is hard-coded to some specific block types.

File: packages/blocks/src/page-block/default/selection-manager/selection-manager.ts (hunk 1 above)
Comment (regischen) [reply packages/blocks/src/page-block/default/selection-manager/selection-manager.ts:39]: ok, I didn't notice there already has one method

File: packages/store/src/workspace/page.ts (hunk 3 above)
Comment (regischen) [reply packages/store/src/workspace/page.ts]: ok, so I move this method to selection manager and turn it to private

File: tests/utils/actions/keyboard.ts [hunk 4]
```diff
@@ -28,7 +28,7 @@ export async function type(page: Page, content: string, delay = 50) {
 export async function withPressKey(
   page: Page,
   key: string,
-  fn: () => Promise<void>
+  fn: () => Promise<void> = () => new Promise(resolve => resolve())
```
Comment (doodlewind) [inline tests/utils/actions/keyboard.ts:31]: This method is designed to run the handler, so if you don't want to pass in the callback, using `pressBackspace` will be semantically a better fit.

Comment (regischen) [reply tests/utils/actions/keyboard.ts]: yeah, I should have found there is pressBackspace method.

**Review by doodlewind — APPROVED** [review]
I think this is a better idea than our discussion result, good job!
