### PR TITLE
fix: copy button of code block menu doesn't work

### LINKED ISSUE #1128: Code block copy does not function as expected
1) Copy paste to the right of the code block I would expect to copy the whole block - but it does not function

2) When copying content from inside the code block it will paste as a code block - I would expect this to only copy the data/string.

Image

### LINKED ISSUE #1145: Copy button of code block menu doesn't work
https://user-images.githubusercontent.com/20554850/218304957-f77a429e-5915-4ae1-b5d3-5ca4dc0a4c4e.mov

### PR DESCRIPTION
**Pull request by qinluhe**
closes https://github.com/toeverything/blocksuite/issues/1145

### CODE REVIEW

File: packages/editor/src/managers/clipboard/copy-cut-manager.ts [hunk 1]
```diff
@@ -216,6 +214,8 @@ export class CopyCutManager {
     } finally {
       tempElem.removeEventListener('copy', listener);
       document.body.removeChild(tempElem);
+
+      const curRange = getCurrentRange();
```
Comment (lawvs) [inline packages/editor/src/managers/clipboard/copy-cut-manager.ts:218]: Please revert this change, it will break copy action in the format bar (selection lost)


https://user-images.githubusercontent.com/18554747/218300412-d4dea242-c77d-4433-97ed-b3a6f93a50b8.mov

**Comment by thorseraq** [comment]
We need further investigation for #1128, key point is `_getClipItems()` during copy, and `_clipboardData2Blocks()` during paste. For example, now hit copy button and paste it at a line end of paragraph, it won't append a new code block.

But it fixes #1145, could you add a unit test in `tests/code.spec.ts`?

**Comment by qinluhe** [comment]
> We need further investigation for #1128, key point is `_getClipItems()` during copy, and `_clipboardData2Blocks()` during paste. For example, now hit copy button of code block and paste it at a line end of paragraph, it won't append a new code block.
> 
> But It fixes #1145, could you add a unit test in `tests/code.spec.ts`?

1. There are two different reasons for the problem that clicking the copy button does not meet expectations, one of which is that the copy event is not passed to handleCopy correctly, this PR fixes the problem for this reason

2. 👌🏻

**Comment by thorseraq** [comment]
@qinluhe I have added the unit test, thanks for contributing! 

we have added the CLA process in BlockSuite. Would you mind signing it by editing on https://github.com/toeverything/blocksuite/edit/master/.github/CLA.md ? Thanks!

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
need to sign up CLA before merging

**Comment by qinluhe** [comment]
> @qinluhe I've added the unit test, thanks for contributing!
> 
> we have added the CLA process in BlockSuite. Would you mind signing it by editing on https://github.com/toeverything/blocksuite/edit/master/.github/CLA.md ? Thanks!
👌🏻
