### PR TITLE
fix(edgeless): frames update in navigation

### LINKED ISSUE #5284: After deleting a frame, the presentation will still display the deleted frame
version：insider /  0.10.0 beta(11.10)

In the following video, four frames are selected in sequence, and then one of them (frame3) is deleted. However, during the presentation, the deleted frame3 will still be displayed.

Image

### PR DESCRIPTION
**Pull request by regischen**
close #5284

### CODE REVIEW

File: packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts [hunk 1]
```diff
@@ -267,23 +270,22 @@ export class EdgelessToolbar extends WithDisposable(LitElement) {
...
+          requestAnimationFrame(() => {
             this._updateFrames();
-          }
-        } else if (e.flavour === 'affine:frame') {
+          });
+        }
+      })
+    );
+    _disposables.add(
+      page.slots.yBlockUpdated.on(e => {
```
Comment (doodlewind) [inline packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts:282]: Better mark this as deprecated, but let's fix this currently.

**Review by doodlewind — APPROVED** [review]
