### PR TITLE
fix(edgeless): copy-as-png not work for nested frame

### LINKED ISSUE #5379: Unexpected behavior when framing other frames
### What happened?

After a third frame (frame 3) around two other frames (1 and 2), when you drag 3, the objects inside 1, and 2 move, but not the frame 

- I added 4 blocks
- Added a frame (1) around two and another frame (2) around two others 
- I added a frame (3) around the two frames 
- When i moved frame 3, the four blocks moved with it, but not frames 1 and 2
This is not what I would expect - Anything including frames inside a frame should be able to be dragged as one group. 

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #5485: Copy as png broken on nested frame
I'm not sure if this is duplicate, if so please close

https://github.com/toeverything/blocksuite/assets/13579374/b9e84320-2322-4e2c-9817-ab3b98538f39

### PR DESCRIPTION
**Pull request by regischen**
close #5485 
close #5379

### CODE REVIEW

File: packages/blocks/src/page-block/edgeless/frame-manager.ts [hunk 1]
```diff
@@ -23,6 +23,16 @@ import { isFrameBlock } from './utils/query.js';
 const MIN_FRAME_WIDTH = 800;
 const MIN_FRAME_HEIGHT = 640;
 const FRAME_PADDING = 40;
+
+export const removeContainedFrames = (frames: FrameBlockModel[]) => {
```
Comment (doodlewind) [inline packages/blocks/src/page-block/edgeless/frame-manager.ts:27]: Please use `export function` by default.

Comment (regischen) [reply packages/blocks/src/page-block/edgeless/frame-manager.ts]: Get it!
