### PR TITLE
fix: create linked doc from block selection loss data

### LINKED ISSUE #6487: 'Create Linked Doc' looses data​
### What happened?

On a page: after creating some content, I wanted to extract to a page via the context menu (see first screenshot)..
Screenshot from 2024-03-15 00-58-42

... I realized, that only the first level bullet points arrived. The other data was lost (see second screenshot). In another example, a quote was also lost.
Screenshot from 2024-03-15 00-59-05

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

_No response_

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell
Affine Version: 0.12.2
Editor Version: 0.12.0-canary-202402220729-0868ac6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by donteatfriedrice**
To fix #6487

### CODE REVIEW

File: packages/blocks/src/root-block/commands/model-crud/get-selected-models.ts [hunk 1]
```diff
@@ -7,9 +7,11 @@ export const getSelectedModelsCommand: Command<
   'selectedModels',
   {
     types?: Extract<BlockSuite.SelectionType, 'block' | 'text' | 'image'>[];
+    mode?: 'all' | 'flat' | 'highest';
```
Comment (doodlewind) [inline packages/blocks/src/root-block/commands/model-crud/get-selected-models.ts:10]: Since this should be part of our public commands API, could you clarify the mode definition in the `/** ... */` comment?

**Review by doodlewind — APPROVED** [review]
Should land this and consider the mode clarification afterwards.
