### PR TITLE
fix(database): can not edit in detail panel

### LINKED ISSUE #4852: Can not edit in detail-panel
image

### PR DESCRIPTION
**Pull request by Flrande**
Close #4852

### CODE REVIEW

File: packages/blocks/src/components/menu/menu.ts [hunk 1]
```diff
@@ -577,7 +577,7 @@ export const createModal = () => {
   div.style.width = '100vw';
   div.style.height = '100vh';
   div.style.zIndex = '1001';
-  document.body.querySelector('block-suite-root')?.append(div);
+  document.body.querySelector('affine-doc-page')?.append(div);
```
Comment (zzj3720) [inline packages/blocks/src/components/menu/menu.ts:580]: Maybe it's better to add a parameter here

**Review by zzj3720 — APPROVED** [review]
