### PR TITLE
fix: embed component lifecycle warning

### LINKED ISSUE #285: Lit lifecycle console warning
Warning message thrown from `pnpm test`:

> Element **embed-block** scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.

@DiamondThree any ideas?

### PR DESCRIPTION
**Pull request by doodlewind**
Fixes #285 

Console warning message:

> reactive-element.ts:76 Element **affine-embed** scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.

/cc @DiamondThree

### CODE REVIEW

File: packages/blocks/src/embed-block/embed-block.ts [hunk 1]
```diff
@@ -47,10 +47,15 @@ export class EmbedBlockComponent extends NonShadowLitElement {
   _caption!: string;
 
   firstUpdated() {
-    this._caption = this.model?.caption ?? '';
-    if (this._caption) {
```
Comment (doodlewind) [inline packages/blocks/src/embed-block/embed-block.ts:51]: @DiamondThree please avoid DOM mutation in `firstUpdated`.
