### PR TITLE
fix(page): copy and paste issues #4545 #4619 #4620

### LINKED ISSUE #4545: Copy and paste inline should not create a new line
https://github.com/toeverything/blocksuite/assets/18554747/50ee6e14-465d-45c3-bc09-395029c9c707

### LINKED ISSUE #4619: The children's content was lost by using drag element to copy
https://github.com/toeverything/blocksuite/assets/13979818/ba1b459b-1ca4-4981-998b-619cdaed475b

### LINKED ISSUE #4620: Wrong Cursor postion displayed after paste
https://github.com/toeverything/blocksuite/assets/13979818/21af4255-725f-4a1f-90d8-5516b9166a5d

### PR DESCRIPTION
**Pull request by BangKk**
close #4545
close #4619
close #4620

### CODE REVIEW

File: packages/blocks/src/__internal__/clipboard/utils/commons.ts [hunk 1]
```diff
@@ -131,7 +131,10 @@ function selectedModels2selectBlocksInfo(
       endPos,
       children: [] as SelectedBlock[],
     };
-    if (model.flavour === 'affine:database') {
+    if (
+      model.flavour === 'affine:database' ||
+      (model.flavour === 'affine:list' && !textSelection)
+    ) {
       const databaseBlock: SelectedBlock = blockModel2selectBlocksInfo(model);
```
Comment (fourdim) [inline packages/blocks/src/__internal__/clipboard/utils/commons.ts:138]: Try rename this variable.

Comment (BangKk) [reply packages/blocks/src/__internal__/clipboard/utils/commons.ts:138]: Ok.

**Comment by BangKk** [comment]
@doodlewind @fourdim @donteatfriedrice Hi, There is a question that needs to be discussed. Which behavior is better in the following two videos? I think B is better.

A:

https://github.com/toeverything/blocksuite/assets/13979818/37119fcf-1148-49e3-ae83-94f3207c880a

B:

https://github.com/toeverything/blocksuite/assets/13979818/ec33909c-f8e3-4a33-9905-eda728bc6101

**Comment by fourdim** [comment]
Personally, I would like to vote for B.
However, we still need to wait other collaborators' suggestions before making a final decision.

File: packages/blocks/src/__internal__/service/json2block.ts [hunk 2]
```diff
@@ -28,131 +28,178 @@ export async function json2block(
...
-        length: 0,
-      });
-    });
-  } else {
-    if (lastModel?.text) {
-      setRange(lastModel, {
-        index: lastModel.text.length,
-        length: 0,
+    const lastBlock = pastedBlocks.at(-1);
+    if (lastBlock?.flavour === 'affine:image' && isFocusedBlockEmpty) {
```
Comment (BangKk) [inline packages/blocks/src/__internal__/service/json2block.ts:95]: This has led to some use cases failing, causing them to assume that the editor content will only contain an image after an image is pasted.

But this will cause cursor lost. So I think there should be an empty block for focus or there already had a paragraph behind the image to focus after the paste.

If you all agree, I'll modify those test cases.

Comment (fourdim) [reply packages/blocks/src/__internal__/service/json2block.ts:95]: This makes sense. Kindly proceed..

File: packages/blocks/src/__internal__/service/json2block.ts [hunk 3]
```diff
@@ -28,131 +28,178 @@ export async function json2block(
...
+  if (splitSuffixModel) {
+    // if split suffix model exit, there must be an merged block
+    assertExists(lastMergedModel);
+
+    lastMergedModel.text?.join(splitSuffixModel.text as Text);
+    page.deleteBlock(splitSuffixModel);
+  }
+
+  /**
+   * After all, wo should handle the caret, there are 3 cases.
```
[the remark this answers is not in the document]
Comment (fourdim) [reply packages/blocks/src/__internal__/service/json2block.ts:151]: Use finally instead of after all will be more appropriate.

File: packages/blocks/src/__internal__/service/json2block.ts [hunk 4]
```diff
@@ -28,131 +28,178 @@ export async function json2block(
...
+      lastMergedModel &&
+        setRange(lastMergedModel, {
+          index: lastMergedModelRangeIndex || 0,
+          length: 0,
+        });
+    });
+  } else {
+    requestAnimationFrame(() => {
+      // TODO: wait block ready
+      lastMergedModel && focusBlockByModel(lastMergedModel);
```
[the remark this answers is not in the document]
Comment (fourdim) [reply packages/blocks/src/__internal__/service/json2block.ts:196]:
```ts
      if (lastMergedModel) {
        const lastMergedBlock = getPageBlock(lastMergedModel);
        if (!lastMergedBlock) {
          return;
        }
        const selectionManager = lastMergedBlock.root.selectionManager;
        const blockSelection = selectionManager?.getInstance('block', {
          path: lastMergedBlock.path ?? [],
        });
        selectionManager.set([blockSelection]);
      }
```

File: packages/blocks/src/__internal__/service/json2block.ts [hunk 5]
```diff
@@ -148,7 +148,7 @@ export async function json2block(
   }
 
   /**
-   * After all, wo should handle the caret, there are 3 cases.
+   * Finally, wo should handle the caret, there are 3 cases.
```
Comment (fourdim) [inline packages/blocks/src/__internal__/service/json2block.ts:151]: typo wo

**Review by fourdim — APPROVED** [review]
