### PR TITLE
fix: ensure change code block language can work

### LINKED ISSUE #1081: code block language perference not persistent
https://user-images.githubusercontent.com/14026360/217725059-8e2af57d-ad36-44d8-9b90-f1f5b450dd9d.mp4

### PR DESCRIPTION
**Pull request by thorseraq**
close #1081

### CODE REVIEW

File: packages/blocks/src/code-block/code-service.ts [hunk 1]
```diff
@@ -11,8 +12,8 @@ export class CodeBlockService extends BaseService {
     this.hljs = await import('highlight.js');
   };
 
-  setLang(model: CodeBlockModel, lang: string) {
-    model.language = lang;
+  setLang(page: Page, model: CodeBlockModel, lang: string) {
+    page.updateBlock(model, { language: lang });
```
Comment (himself65) [inline packages/blocks/src/code-block/code-service.ts]: use model.page.updateBlock

**Review by doodlewind — APPROVED** [review]
