### PR TITLE
fix(edgeless): fix delete and select-all when active

### LINKED ISSUE #3031: Overkill cmd-A binding inside active frame

### LINKED ISSUE #3032: Overkill delete key binding inside active frame

### PR DESCRIPTION
**Pull request by regischen**
close #3031 
close #3032

fix bugs
command + a select all overkill when active
delete overkill when active

### CODE REVIEW

File: tests/utils/actions/misc.ts [hunk 1]
```diff
@@ -944,3 +944,9 @@ export async function transformHtml(page: Page, data: string) {
   );
   return await promiseResult;
 }
+
+export function isDOMRectSame(a: DOMRect, b: DOMRect) {
```
Comment (doodlewind) [inline tests/utils/actions/misc.ts:948]: The API design here looks a bit verbose.

**Review by doodlewind — APPROVED** [review]
LGTM, thanks for the timely fix!
