### PR TITLE
fix: enter key should as expected after setting heading by shortkey

### LINKED ISSUE #4987: After using shortcut keys to set headings, using the Enter key will clear the content
The following screen recording is the effect after using the setting Heading 1 in the Internal version.

https://github.com/toeverything/blocksuite/assets/22443345/bdf80e43-f7cf-4858-8c6b-c8c839d49203

### PR DESCRIPTION
**Pull request by lzlme**
fix #4987

### CODE REVIEW

File: packages/blocks/src/page-block/utils/callback.ts [hunk 1]
```diff
@@ -17,10 +17,13 @@ export async function onModelTextUpdated(
   await richText.updateComplete;
   const vEditor = richText.vEditor;
   assertExists(vEditor, 'VEditor is not ready yet.');
-  vEditor.slots.updated.once(() => {
-    if (callback) {
-      callback(richText);
-    }
+  await new Promise<void>(resolve => {
```
Comment (doodlewind) [inline packages/blocks/src/page-block/utils/callback.ts:20]: This seems to be simply a `queueMicrotask` alternative. But semantically here shall we wait for an extra tick here? This may lose emitted events and potentially break other behavior.

Comment (lzlme) [reply packages/blocks/src/page-block/utils/callback.ts:20]: Yes, I'll look into it further.

**Review by Flrande — APPROVED** [review]
