### PR TITLE
fix: zoom in/out shortcut key on mac should be metakey

### LINKED ISSUE #1652: The Zoom in/out shortcut key for Edgeless on Mac should be ⌘ + scroll wheel, not Ctrl + scroll wheel
However, on Windows, it is still Ctrl + scroll wheel.

### PR DESCRIPTION
**Pull request by hanchayi**
Close #1652

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
Good catch, thanks!

File: packages/blocks/src/__internal__/utils/index.ts [hunk 1]
```diff
@@ -14,5 +14,6 @@ export * from './lit.js';
 export * from './query.js';
 export * from './rect.js';
 export * from './selection.js';
+export * from './shortcut.js';
```
Comment (doodlewind) [inline packages/blocks/src/__internal__/utils/index.ts:17]: According to CI log, this is better not be exposed at top level since it breaks SSR by accessing `navigator`.

**Comment by doodlewind** [comment]
Merged, thanks for your contribution!
