### PR TITLE
fix(blocks): move h1-h6 paragraph children into parent

### LINKED ISSUE #1074: move h1-h6 paragraph children into parent
> In my opinion
> So far we don't allow headings blocks have child-item, the expected effect is that:
> **After changing the paragraph style to headings, its child-items is no longer child-item.**
> And this apply to other block style which is not allowed have child-item

Refs: https://github.com/toeverything/blocksuite/issues/1059#issuecomment-1422040873

### PR DESCRIPTION
**Pull request by Flrande**
Close #1074

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]

File: packages/blocks/src/paragraph-block/paragraph-service.ts [hunk 1]
```diff
@@ -34,6 +35,24 @@ export class ParagraphBlockService extends BaseService {
         return text;
     }
   }
+
+  /**
+   * side effect when update block type
+   */
+  updateTypeEffect(model: ParagraphBlockModel, newType: string) {
+    // if change to header, move all children to parent level
+    if (newType.startsWith('h')) {
```
Comment (lawvs) [inline packages/blocks/src/paragraph-block/paragraph-service.ts:44]: You should use `isSupportChildren`

https://github.com/toeverything/blocksuite/blob/fb42cf1ce0c0ff6b4ae9fa8486fb366957e639ea/packages/blocks/src/__internal__/utils/std.ts#L6-L20

Comment (Flrande) [reply packages/blocks/src/paragraph-block/paragraph-service.ts:44]: I will update it in the next pr, where I will add test as well.
