### PR TITLE
fix(blocks): fix keyboard handler when in edgeless mode

### LINKED ISSUE #1616: Error when press hotkey in edgeless
Steps to reproduce

- Switch to edgeless
- Focus text
- Click an empty area
- Press any hotkey(`ArrowRight`/`Space`)

https://github.com/toeverything/blocksuite/blob/a8e43d2fe92a5e410340cce43dffce46f3eac95e/packages/blocks/src/__internal__/rich-text/keyboard.ts#L539

Screenshot 2023-03-09 at 5 34 42 PM

### PR DESCRIPTION
**Pull request by Flrande**
Close #1616

### CODE REVIEW

File: packages/blocks/src/__internal__/rich-text/keyboard.ts [hunk 1]
```diff
@@ -536,12 +536,17 @@ export function createKeyDownHandler(
...
+      const range = getCurrentNativeRange();
+      if (!range) return;
+      if (
+        !vEditor.rootElement.contains(range.startContainer) ||
+        !vEditor.rootElement.contains(range.endContainer)
+      ) {
+        return;
+      }
+    } catch (error) {
+      // try...catch is used to avoid error when in edgeless mode
```
Comment (lawvs) [inline packages/blocks/src/__internal__/rich-text/keyboard.ts:549]: We should not ignore any error

**Review by lawvs — CHANGES_REQUESTED** [review]

**Review by doodlewind — APPROVED** [review]

**Review by doodlewind — APPROVED** [review]
