### PR TITLE
fix: console error exporting PNG/PDF in playground

### LINKED ISSUE #3115: Console error exporting PNG/PDF in playground
Console error: 

```
index.ts:145 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5173/node_modules/.vite/deps/html2canvas.js?v=db7c62c1
```

### PR DESCRIPTION
**Pull request by zuoxiaodong0815**
close #3115 

fix: console error exporting PNG/PDF.
fix: the pdf file is too big.
fix: checked that the images have been displayed.

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]

File: packages/blocks/src/__internal__/content-parser/index.ts [hunk 1]
```diff
@@ -1,12 +1,15 @@
 import { assertExists } from '@blocksuite/global/utils';
+import type { IBound } from '@blocksuite/phasor';
 import type { BaseBlockModel, Page } from '@blocksuite/store';
 import { Slot } from '@blocksuite/store';
 import { marked } from 'marked';
 
+import { xywhArrayToObject } from '../..//page-block/edgeless/utils.js';
```
Comment (fourdim) [inline packages/blocks/src/__internal__/content-parser/index.ts:7]: It seems that something is wrong here.
