### PR TITLE
fix: use manual shallow copy on `DOMRect`

### LINKED ISSUE #632: Image selection state shelters the blocks above
When an image is inserted into the page and is selected, the blocks above (red frame in the screenshot) are not clickable.

image

This is introduced in #606

### PR DESCRIPTION
**Pull request by JimmFly**
Fixes #632

### CODE REVIEW

File: packages/blocks/src/page-block/default/utils.ts [hunk 1]
```diff
@@ -68,12 +68,15 @@ export function getBlockEditingStateByPosition(
...
+    const copyRect = (rect: DOMRect) => {
+      const { top, right, bottom, left, width, height, x, y } = rect;
+      return { top, right, bottom, left, width, height, x, y };
+    };
     if (hasOptionBar(block)) {
       const currentHoverDom =
         block.type === 'image' ? hoverDom?.querySelector('img') : hoverDom;
       blockRect = currentHoverDom?.getBoundingClientRect() as DOMRect;
-      detectRect = { ...blockRect } satisfies DOMRect;
+      detectRect = copyRect(blockRect) as DOMRect;
```
Comment (lawvs) [inline packages/blocks/src/page-block/default/utils.ts:79]: why does it work?

**Review by lawvs — CHANGES_REQUESTED** [review]

**Review by Himself65 — APPROVED** [review]

File: packages/blocks/src/page-block/default/utils.ts (hunk 1 above)
Comment (Himself65) [reply packages/blocks/src/page-block/default/utils.ts:79]: https://stackoverflow.com/questions/42713229/getboundingclientrect-object-properties-cannot-be-copied

Comment (himself65) [reply packages/blocks/src/page-block/default/utils.ts]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#querying_object_properties
